show_category_name:
  type: bool
  default: true
  description: 'Show category the category name heading'
  
show_category_description: 
  type: bool
  default: true
  description: 'Show first paragraph of the category description text<br>This is taken from the about this category Topic'
  
align_text:
  type: enum
  default: left  
  choices:
  - left
  - center
  - right     
  description: 'Alignment of the text within the category header'  
  
show_category_logo:
  type: bool
  default: true
  description: 'Show the category logo image within the header'
  
show_site_logo:
  type: bool
  default: true
  description: 'Show the small site logo if a logo is not set'  
  
align_logo:
  type: enum
  default: left  
  choices:
  - left
  - center
  - right
  description: 'Position of the logo within the header. Center display the logo at the top above the text'  
  
size_logo:
  type: enum
  default: normal  
  choices:
  - small
  - normal
  - original
  description: 'Position of the logo within the header. Center display the logo at the top above the text'    
  
header_border_style:
  type: enum
  default: box  
  choices:
  - none
  - box
  description: 'Set whether to display the header in a box, similar in style to the default subcategory box with a left border colour'
  
   
header_background_color:
  type: enum
  default: none  
  choices:
  - none
  - category
  - theme
  description: 'Set the background color to your header<br>Category: sets it to the category background color<br>Theme: uses you theme primary color settings'
  
header_background_opacity:
  type: enum
  default: 25%  
  choices:
  - 10%
  - 25%
  - 50%
  - 75%
  - 100%
  description: 'Set the background color opacity. 100% is full color. A lesser percent allows the color to adjust to light and dark themes' 
  
