show_category_name:
  type: bool
  default: true
  description: 'Show category the category name heading'
  
show_category_description: 
  type: bool
  default: true
  description: 'Show first paragraph of the category description text<br>This is taken from the about this category Topic'
  
align_text:
  type: enum
  default: left  
  choices:
  - left
  - center
  - right     
  description: 'Alignment of the text within the category header'  
  
show_category_logo:
  type: bool
  default: true
  description: 'Show the category logo image within the header'
  
show_site_logo:
  type: bool
  default: true
  description: 'Show the small site logo if a logo is not set'  
  
position_logo:
  type: enum
  default: left  
  choices:
  - left
  - right
  - top
  description: 'Position of the logo within the header. Top displays the logo above the text'  
  
size_logo:
  type: enum
  default: standard  
  choices:
  - standard
  - small  
  - original
  description: 'Position of the logo within the header.<br>Small is 40px high similar to a suncategory box logo<br>Standard is 150px high<br>Original is the size of the image uploaded'    
  
header_border_style:
  type: enum
  default: box  
  choices:
  - box
  - none
  description: 'Set whether to display the header in a box, similar in style to the default subcategory box with a left border colour'
   
header_background_color:
  type: enum
  default: none  
  choices:
  - none
  - category
  - theme
  description: 'Set the background color to your header<br>Category: sets it to the category background color<br>Theme: uses you theme primary color settings'
  
header_background_image:
  type: enum
  default: contain  
  choices:
  - cover
  - contain
  - resize
  - outside
  description: 'Applies if you have uploaded a category background image<br>Cover, contain and resize display the background in the header<br>Outside is the Discourse default displaying it outside the header.'

show_subcategory: 
  type: bool
  default: true
  description: 'Show header for subcategories'  
  
show_parent_category_name: 
  type: bool
  default: true
  description: 'Show parent category on subcategory headers'    
  
show_parent_category_logo:
  type: bool
  default: true
  description: 'Show parent logo in subcategories where a logo is not set'
  
show_if_no_category_description: 
  type: bool
  default: true
  description: 'Show header if category description is not set'  

show_mobile: 
  type: bool
  default: true
  description: 'Show category header on mobile devices'

category_exceptions:
  type: list
  default: '' 
  description: 'Headers will not show for these categories'



