show_category_name:
  type: bool
  default: true
  description: 'Show category the category name heading'

show_category_description: 
  type: bool
  default: true
  description: 'Show first paragraph of the category description text\nThis is take from the about this category Topic'
  
align_text:
  type: enum
  default: left  
  choices:
  - left
  - center
  - right     
  
show_category_logo:
  type: bool
  default: true
  description: 'Show the category logo image within the header'
  
show_site_logo:
  type: bool
  default: true
  description: 'Show the small site logo if a logo isn't set'  
  
align_logo:
  type: enum
  default: left  
  choices:
  - left
  - center
  - right
  description: 'Poistion of the logo within the header. Center display the logo at the top above the text'  
  
size_logo:
  type: enum
  default: normal  
  choices:
  - small
  - normal
  - original
  description: 'Position of the logo within the header. Center display the logo at the top above the text'    
  
header_border_style:
  type: enum
  default: box  
  choices:
  - none
  - box
  description: 'Set whether to display the header in a box, similar in style to the default subcategpory boxes with a left border color.'
  
header_background_color:
  type: enum
  default: none  
  choices:
  - none
  - category
  - theme
  description: 'Set the background color to your header\nCategory: sets it to the category background color\nTheme: uses you theme primary color settings'
  
header_background_opacity:
  type: enum
  default: 25%  
  choices:
  - 10%
  - 25%
  - 50%
  - 75%
  - 100%
  description: 'Set the background color opacity. 100% is full color. A lesser percent allows the color to adjust to light and dark themes.' 
  
header_background_image:
  type: enum
  default: contain  
  choices:
  - cover
  - contain
  - resize
  - outside
  description: 'Applies if you have uploaded a category background image\nCover, contain and resize display the background in the header\n Outside is the Discourse default displaying it outside the header.'

show_subcategory: 
  type: bool
  default: true
  description: 'Show header for subcategories'  
  
show_parent_category_name: 
  type: bool
  default: true
  description: 'Show parent category as a breadcrum on subcategory headers\nDisplays as Parent Category Name: Subcategory Name\nThe parent category name is clickable as a link to the parent catgeory page'    
  
show_parent_category_logo:
  type: bool
  default: true
  description: 'Show the parent category logo in subcategories if a logo isn't set. Otherwise defaults to site logo or none.'
  
hide_if_no_category_description: 
  type: bool
  default: false
  description: 'Hide header if category description is not set'  

show_mobile: 
  type: bool
  default: true
  description: 'Show category header on mobile devices'

category_exceptions:
  type: list
  default: '' 
  description: 'Headers will not show for these categories'
